### ISSUE TITLE
SCHED failing in load_coarse_dynspecs

### ISSUE THREAD

**Issue by d-r-scott** [askap-craco/CELEBI#470]
Encountered for FRB200906.

Final error message:
```
python3 /fred/oz002/askap/craft/craco/CELEBI/beamform/craftcor_tab.py -d /fred/oz002/askap/craft/craco/processing/data/200906/frb --parset /fred/oz002/askap/craft/craco/processing/data/200906/fcm.txt --calcfile c1_f0/craftfrb.im -o 200906_ICS --ics --cpus=8 --pol=X --an=0
Traceback (most recent call last):
  File "/fred/oz002/askap/craft/craco/CELEBI/beamform/craftcor_tab.py", line 826, in <module>
    _main()
  File "/fred/oz002/askap/craft/craco/CELEBI/beamform/craftcor_tab.py", line 43, in _main
    calcresults = ResultsFile(values.calcfile)
  File "/fred/oz002/askap/craft/craco/craft-python/calc11.py", line 192, in __init__
    with open(self.fname, 'rU') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c1_f0/craftfrb.im'
```

SCHED error in askap2difx:
```
 * SOURCE='CRAFTSRC' RA=[RA] DEC=[DEC] REMARKS='Beam centre for dumped voltage data' /
 +++ERROR+++ Not a valid number
SRFINISH: CRAFTSRC     not in catalogs, ephemeris or satellite file.
                       No planetary ephemeris specified.
                       No satellite info specified.
      Note some source names have changed.  Look for close matches.
 
SRFINISH: Missing sources.
```

**Comment by d-r-scott** [comment]
`craftfrb.key` file looks fine when compared to working run for 210117
