### ISSUE TITLE
mergeOversampledDiFX.py AssertionError: ncurr < target_nchan

### ISSUE THREAD

**Issue by d-r-scott** [askap-craco/CELEBI#471]
Encountered for FRB201124a.3

```
  Traceback (most recent call last):
    File "/fred/oz002/askap/craft/craco/difx/sites/ASKAP/mergeOversampledDiFX.py", line 788, in <module>
      stitchVisibilityfile(difxf,cfg)
    File "/fred/oz002/askap/craft/craco/difx/sites/ASKAP/mergeOversampledDiFX.py", line 557, in stitchVisibilityfile
      assert(ncurr < target_nchan)
  AssertionError
```

**Comment by d-r-scott** [comment]
None of the voltage files are shorter than expected - running without ak15 and seeing what happens

**Comment by d-r-scott** [comment]
Dropped ak15 and then same error happens for ak07-ak18 baseline. Dropped ak07 instead and it happens for ak08-ak15. Maybe it's more to do with the time than the frb? This is only happening for the polcal so I'll keep going without it for now

**Comment by d-r-scott** [comment]
Nope, happens for the FRB too

**Comment by adamdeller** [comment]
can you point to the working directory?

**Comment by d-r-scott** [comment]
@adamdeller 
`/fred/oz002/askap/craft/craco/processing/work/201124a.3/7a/05e9b88854dc54afaf73a567021c10`

**Comment by adamdeller** [comment]
Okay something weird is going on here. In the .difx/ file, there is an extra set of visibilities for the first integration of baselines to the second antenna. This "bonus" visibility seems to have near-zero weight and zero amplitude, and I'm wondering if it has been incorrectly added by padDiFX.

**Comment by adamdeller** [comment]
Ah yes I see there is an _old.difx, which is presumably from before padDiFX, and it doesn't have this ghost visibility.  I think I need to look at padDiFX - I think it must be doing something bad!

**Comment by adamdeller** [comment]
Hi Danica, the c2_f0 correlation and the c1_f0 reference correlation don't match: the c1_f0 has 20 antennas, while the c2_f0 one has 21! This is why fillDiFX is falling over. Can you check why this might be the case?

**Comment by d-r-scott** [comment]
This doesn't seem to be an error with the data itself, the data has 21 antennas worth of c1_f0 vcraft files
